title: Dawson Haddox
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
show_downloads: false
google_analytics: true
twitter: https://x.com/DawsonHaddox
# cv: /assets/documents/HaddoxCVJuly2024.pdf
# banner:
