title: Dawson Haddox
logo: /assets/img/Logo.png
theme: jekyll-theme-minimal
show_downloads: true
google_analytics: G-F1S9FK6PSF
bluesky: https://x.com/DawsonHaddox
email: dawson.d.haddox.25@dartmouth.edu
cv: /assets/documents/DawsonHaddoxblCV_November2024.pdf