title: Dawson Haddox
logo: /assets/img/logo.JPG
theme: jekyll-theme-minimal
show_downloads: true
google_analytics: G-F1S9FK6PSF
twitter: https://x.com/DawsonHaddox
email: dawson.d.haddox.25@dartmouth.edu
cv: /assets/documents/DawsonHaddoxCV_July2024.pdf